### ISSUE TITLE
FF needs API key for output handler notebook?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide-examples#9]
@mdboom, hve you encountered this-- in this example notebook:
https://iodide-project.github.io/iodide-examples/output-handling.html
several of the outputs that are supposed to render as maps often render as broken links in FF. 

when i try to open the image url in a new tab, I get:
`The Google Maps API server rejected your request. This service requires an API key.`

Doesn't seem to be a problem in Chrome... looks like anti-trusty behavior to me...

**Comment by mdboom** [comment]
This is the first time I've seen this and I've been using it a lot for testing.  But alas, I'm able to reproduce as well.

I note that the docs now say:

![image](https://user-images.githubusercontent.com/38294/36903325-6b962058-1dfb-11e8-8fac-f17d73a41069.png)

So it looks like a token is required now.  FWIW, I'm seeing the breakage on Chrome as well now, so maybe it just took a while for the new requirement to roll out rather than anything nefarious...  (But who knows, really).

I'm not sure how to handle this -- I don't think we want to just register a token and then post it publicly in our example.  But asking users to go get their own token and plugging it in also makes for a cumbersome demo.  Sort of out of my area of expertise...

**Comment by mdboom** [comment]
Some alternatives:

http://staticmap.openstreetmap.de/

Or something interactive (that doesn't seem to require a key to fetch the map tiles):

http://leafletjs.com/
